name: Update blog posts in README.md
on:
  schedule: 
  - cron: '0 0/6 * * *'
  workflow_dispatch: 

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Get posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://themkat.net/feed.xml"
          max_post_count: 5

      - name: Get youtube video list
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC_3sv9P5H8wShL1cRnsHDjA"
          comment_tag_name: YOUTUBE-LIST
          max_post_count: 5
          
